Core/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from Core import views
from Core.admin import admin_panel
from Products import views as views_product
from ProjectOnlineMarket import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin_panel/', admin_panel.urls),
    url(r'^$', views.home, name='home'),
    url(r'^basket/', include('Baskets.urls')),
    url(r'^order/', include('Orders.urls')),
    url(r'^authentication/', include('Authentication.urls')),
    url(r'^personal_room/', include('PersonalRoom.urls')),
    url(r'^product/', include('Products.urls')),
    url(r'^catalog/$', views_product.category_list, name='category_list'),
    url(r'^catalog/(?P<category_name_url>\w*)/$', views_product.category_detail, name='category_detail'),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^search/$', views.search, name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from django.db import models


class Visitation(models.Model):
    ip = models.GenericIPAddressField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return 'IP: %s' % self.ip

    class Meta:
        verbose_name = 'Посещение'
        verbose_name_plural = 'Посещения'


class SlideBanner(models.Model):
    slide = models.ImageField('Загрузка нового слайда', upload_to='banner',
                              help_text='ВНИМАНИЕ! Для корректного отображения необходимо загружать изображения 760x350')

    def __str__(self):
        return str(self.slide)

    class Meta:
        verbose_name = 'Слайд баннера'
        verbose_name_plural = 'Слайды баннера'

Products/models.py
from PIL import Image as Im
from django.db import models
from django.urls import reverse

_MAX_SIZE = 150
_MAX_SIZE_2 = 500
UPLOAD_IMG_PRODUCTS = 'products/'

DICT_LETTERS = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'ye', 'ё': 'yo', 'ж': 'zh', 'з': 'z',
                'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
                'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'shch',
                'ъ': '', 'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya', ' ': '_', '-': '_', ',': '_',
                '"': '_', '(': '_', ')': '_', '№': '_'}


class SettingsProduct(models.Model):
    proteins = models.CharField('Белки', max_length=30, blank=True, null=True)
    fats = models.CharField('Жиры', max_length=30, blank=True, null=True)
    carbohydrates = models.CharField('Углеводы', max_length=30, blank=True, null=True)
    caloric_value = models.CharField('Калорийность', max_length=30, blank=True, null=True)
    net_weight = models.CharField('Вес нетто', max_length=30, blank=True, null=True)
    packaging = models.CharField('Упаковка', max_length=30, blank=True, null=True)
    shelf_life = models.CharField('Срок хранения', max_length=30, blank=True, null=True)
    manufacturer = models.CharField('Производитель', max_length=50, blank=True, null=True)
    manufacturer_country = models.CharField('Страна производитель', max_length=50, blank=True, null=True)
    trademark = models.CharField('Торговая марка', max_length=50, blank=True, null=True)
    product_name = models.CharField('Название продукта', max_length=300, blank=True, null=True)

    def __str__(self):
        return 'Характеристики %s' % self.product_name

    def all(self):
        return [[field.verbose_name, self.__dict__[field.name]] for field in self._meta.get_fields()[2:-1]]

    class Meta:
        verbose_name = 'Характеристика продукта'
        verbose_name_plural = 'Характеристики продуктов'


class Category(models.Model):
    name = models.CharField('Название', max_length=40)
    name_url = models.CharField('URL', max_length=50, default='')

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        name_url = ''
        self.name = self.name.lower()
        for letter in self.name:
            try:
                name_url += DICT_LETTERS[letter]
            except KeyError:
                name_url += letter
        self.name_url = name_url
        self.name = self.name[0].upper() + self.name[1:]
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_name_url': self.name_url})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField('Название', max_length=300, default='')
    category = models.ManyToManyField(Category, related_name='category', verbose_name='Категория')
    price = models.IntegerField('Цена', default=0)
    new_price = models.IntegerField('Новая цена', blank=True, null=True)
    sail_procent = models.IntegerField('Скидка', blank=True, null=True)
    weight = models.IntegerField('Вес', default=0)
    availability = models.BooleanField('Доступность', default=True)
    sold = models.PositiveIntegerField('Продано', default=0)
    number = models.PositiveIntegerField('В наличии')
    settings = models.ForeignKey(SettingsProduct, verbose_name='Характеристики', on_delete=models.CASCADE)
    description = models.TextField('Описание', default='', blank=True, null=True)
    date = models.DateField('Дата добавления', auto_now_add=True)
    name_url = models.CharField('URL', max_length=500, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail_product', kwargs={'name_url': self.name_url})

    def icon_value(self):
        """
        0 - значение NEW
        1 - значение HIT
        """
        category = list(map(lambda x: x[1], self.category.values_list()))
        result = ''
        if 'Новинки' in category:
            result += '0'
        if 'Хит продаж' in category:
            result += '1'

        return result

    def save(self, *args, **kwargs):

        name_url = ''
        self.name = self.name.lower()
        for letter in self.name:
            try:
                name_url += DICT_LETTERS[letter]
            except KeyError:
                name_url += letter
        self.name_url = name_url
        self.name = self.name[0].upper() + self.name[1:]

        if self.new_price:
            self.sail_procent = 100 - int(self.new_price / self.price * 100)

        if self.number:
            self.availability = True
        else:
            self.availability = False

        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


def directory_path(instance, filename):
    return 'products/{0}/{1}'.format(instance.product.name_url, filename)


class ImageProduct(models.Model):

    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    image = models.ImageField('Файлы', upload_to=directory_path,
                              help_text='Можно выбрать несколько (Ctrl или выделение)')
    image_resize = models.CharField(max_length=1000, default='', blank=True)

    def __str__(self):
        return '%s' % self.product

    def save(self, *args, **kwargs):

        original_image = directory_path(self, self.image).split('.')
        self.image_resize = original_image[0] + '-2.' + original_image[1]

        super(ImageProduct, self).save(*args, **kwargs)

        filename = self.image.path
        width = self.image.width
        height = self.image.height
        max_size = max(width, height)
        image = Im.open(filename)
        image_small = image.resize(
            (round(width / max_size * _MAX_SIZE),
             round(height / max_size * _MAX_SIZE)),
            Im.ANTIALIAS
        )
        filename_2 = filename.split('.')
        img_resize = filename_2[0] + '-2.' + filename_2[1]
        image_small.save(img_resize)
        if max_size > _MAX_SIZE_2:
            image_big = image.resize(
                (round(width / max_size * _MAX_SIZE_2),
                 round(height / max_size * _MAX_SIZE_2)),
                Im.ANTIALIAS
            )
            image_big.save(filename)

    class Meta:
        verbose_name = 'Фотографии продукта'
        verbose_name_plural = 'Фотографии продуктов'

Core/views.py
from django.http import JsonResponse
from django.shortcuts import render

from Core.models import SlideBanner
from Products.models import *


def home(request):
    hit = 'Новинки'
    new = 'Хит продаж'
    products = Product.objects.filter(category__name__in=[hit, new]).distinct()[:20]
    slides = SlideBanner.objects.all()[::-1]
    return render(request, 'home.html', locals())


def search(request):
    products = Product.objects.all()
    data = {}
    if request.POST['input']:
        for n, product in enumerate(products):
            if request.POST['input'] in product.name.lower():
                data[str(n)] = (product.name, product.name_url)
    return JsonResponse(data)

Core/templates/banner.html
<div class="col-md-12" style="padding: 0 0 0 3px">
    <div class="banner">
        <div class="slider">
            {% for slide in slides %}
                <div class="element-slider">
                    <img src="{{ url }}/media/{{ slide }}" alt="">
                </div>
            {% endfor %}
        </div>
        <div id="button-slider-left">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </div>
        <div id="button-slider-right">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </div>
        <div id="progressbar-slide"></div>
    </div>
</div>

Core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '../static/css/market.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//malsup.github.com/jquery.form.js"></script>
    <script src="{% static '../static/js/base.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Barlow+Condensed" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<div class="container">
    {% include 'welcome_block.html' %}
    <header>
        <div class="row">
            <div class="col-xs-12">
                <div class="header">
                    {% block head %}{% include 'head.html' %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="row" style="margin: 0; padding: 12px 0 12px 0;">
            <div class="col-xs-2 col-xs-2-5" style="padding: 0">
                <a href="/catalog/" class="category-href">
                    <div class="category one-cat">
                        Каталог
                    </div>
                </a>
            </div>
            <div class="col-xs-2 col-xs-2-5" style="padding: 0">
                <a href="/catalog/novinki/" class="category-href">
                    <div class="category">
                        Новинки
                    </div>
                </a>
            </div>
            <div class="col-xs-2 col-xs-2-5" style="padding: 0">
                <a href="/catalog/hit_prodazh/" class="category-href">
                    <div class="category">
                        Хит продаж
                    </div>
                </a>
            </div>
            <div class="col-xs-2 col-xs-2-5" style="padding: 0">
                <a href="/" class="category-href">
                    <div class="category">
                        Акции
                    </div>
                </a>
            </div>
            <div class="col-xs-2 col-xs-2-5" style="padding: 0">
                <a href="/catalog/rasprodazha/" class="category-href">
                    <div class="category">
                        Распродажа
                    </div>
                </a>
            </div>
        </div>
    </header>
    <body>
    <div class="row">
        {% block middle %}
            <div class="col-xs-3" style="padding: 0 15px 0 15px">
                <div class="leftbar">
                    {% block leftbar %}{% include 'leftbar.html' %}{% endblock %}
                </div>
            </div>
            <div class="col-xs-9" style="padding: 0 15px 0 15px">
                <div class="content">
                    {% block content %}
                        {% block information %}
                            {% include 'banner.html' %}
                        {% endblock %}
                        <div class="col-md-12">
                            <div class="content">
                                <div id="product-list" class="row">
                                    {% for product in products %}
                                        {% include 'products_list.html' %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endblock %}
                </div>
            </div>
            </div>
        {% endblock %}
    <div onclick="location.href='/basket/'" id="hide-basket">
        <p><i class="fa fa-shopping-cart" style="color: #ff9a06; font-size: 21px" aria-hidden="true"></i>
            <span>Товаров:</span> <b id="hide-basket-count">{{ number_product_in_basket }}</b>
            <span>На сумму:</span>
            <b id="hide-basket-total">{{ total_amount }} р.</b></p>
    </div>
    <div id="modal-window-for-favorite">
        <h3 style="font-weight: bold; color: green">Продукт успешно добавлен в избранное!</h3>
        <i class="fa fa-star-o" aria-hidden="true" style="font-size: 140px"></i>
        <h4 style="margin: 20px 0 20px 0">Этот товар теперь можно увидеть в личном кабинете!</h4>
        <button class="btn btn-success" id="next-buy" style="font-size: 20px">Продолжить покупки</button>
        <button onclick="window.location='/personal_room/favorites/'" class="btn btn-warning" style="font-size: 20px">Перейти в ЛК</button>
        <div id="close-modal"><span class="glyphicon glyphicon-remove"></span></div>
    </div>
    <div id="modal-window-no-auth">
        <p>Необходимо <b>авторизоваться</b>. <a href="/authentication/login/">Войдите</a>, или <a href="/authentication/register/">зарегистрируйтесь</a>.</p>
        <div id="close-modal"><span class="glyphicon glyphicon-remove"></span></div>
    </div>
    <div id="mask"></div>
    <div id="small-modal-window">
        <p></p>
    </div>
    <div id="result-search">
        <h4 style="padding-left: 15px">Результаты поиска:</h4>
        <p style="margin: 0"></p>
    </div>
    </body>
    <footer>
        <div class="row">
            <div class="col-xs-12" style="padding: 0">
                <div class="footer">
                    {% block footer %}{% include 'footer.html' %}{% endblock %}
                </div>
            </div>
        </div>
    </footer>
</div>
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function change_button(button) {
        var parent_button = button.parent();
        parent_button.parent().children('.count-product').remove();
        button.remove();
        parent_button.append('<button onclick="location.href=\'/basket\'" type="button" class="btn btn-info">Товар в корзине</button>')
    }
</script>
</html>

Core/templates/footer.html
<div class="row">
    <div class="col-xs-4">
        <div class="navigation">
            <p class="footer-tittle">Навигация</p>
        </div>
        <div class="col-xs-6">
            <ul class="nav" style="float: right">
                <li class="change-color"><a href="#"><i class="fa fa-home" aria-hidden="true"></i> Главная</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i> Вход</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-eye" aria-hidden="true"></i> О магазине</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-truck" aria-hidden="true"></i> Доставка</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-credit-card" aria-hidden="true"></i> Оплата</a></li>
            </ul>
        </div>
        <div class="col-xs-6">
            <ul class="nav" style="float: right">
                <li class="change-color"><a href="#"><i class="fa fa-bullhorn" aria-hidden="true"></i> Акции</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-phone" aria-hidden="true"></i> Контакты</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-info-circle" aria-hidden="true"></i> Помощь</a></li>
                <li class="change-color"><a href="#"><i class="fa fa-user" aria-hidden="true"></i> Регистрация</a></li>

            </ul>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="row" style="margin-bottom: 15px">
            <div style="display: inline-block; width: 100px; margin-left: 50px; vertical-align: middle">
                <i class="fa fa-truck icon-footer" style="font-size: 70px; color: #ea8d11;" aria-hidden="true"></i>
            </div>
            <div style="display: inline-block; width: 150px; vertical-align: middle">
                Доставка Почтой России в <b>любой населенный пункт РФ</b>
            </div>
        </div>

        <div class="row" style="margin-bottom: 15px">
            <div style="display: inline-block; width: 100px; margin-left: 50px; vertical-align: middle">
                <i class="fa fa-car icon-footer" style="font-size: 70px; color: green;" aria-hidden="true"></i>
            </div>
            <div style="display: inline-block; width: 150px; vertical-align: middle">
                Выдача заказов в пунктах самовывоза в <b>более чем 90 городах</b>
            </div>
        </div>

        <div class="row" style="margin-bottom: 15px">
            <div style="display: inline-block; width: 100px; margin-left: 50px; vertical-align: middle">
                <i class="fa fa-th-large icon-footer" style="font-size: 70px;" aria-hidden="true"></i>
            </div>
            <div style="display: inline-block; width: 150px; vertical-align: middle">
                <div>Широкий выбор товаров для <b>здорового образа жизни</b></div>
            </div>
        </div>
    </div>
    <div style="padding-right: 24px" class="col-xs-4">
        <p class="footer-tittle">Способы оплаты</p>
        <p>Вы можете оплатить заказ наличными, пластиковой картой, через Яндекс.Деньги,
            Webmoney и в отделениях Почты России</p>
        <img src="{{ url }}/media/image/яндекс.gif" alt="">
        <img src="{{ url }}/media/image/wm.png" alt="">
        <img width="120" src="{{ url }}/media/image/pay.jpg" alt="">

        <p style="margin-top: 20px" class="footer-tittle">Социальные сети</p>
        <a href="" class="social-media">
            <img src="{{ url }}/media/image/vk.png" alt="">
        </a>
        <a href="" class="social-media">
            <img src="{{ url }}/media/image/google.png" alt="">
        </a>
        <a href="" class="social-media">
            <img src="{{ url }}/media/image/facebook.png" alt="">
        </a>
        <a href="" class="social-media">
            <img src="{{ url }}/media/image/instagram.png" alt="">
        </a>
    </div>
</div>

Core/templates/head.html
<div class="head">
    <a id="logo" href="/"><div class="logo"></div>
        <div class="slogan">Магазин<br>здорового<br>питания</div>
    </a>
    <div class="head-info">
        <p class="phone">8 (800) 555-35-35</p>
        <p class="change-color" style="margin: 0; font-size: 13px; line-height: 1.9">(Звонок по России бесплатный)<br>
            пн-пт: <b>9:00-21:00</b>, сб,вс: <b>11:00-21:00</b> <br>
        </p>
        <div style="margin-top: 5px">
            <i class="fa fa-search" style="color: darkgrey" aria-hidden="true"></i>
            <input id="search" style="display: inline-block" class="form-control" placeholder="Поиск продуктов..." type="text">
        </div>
    </div>
    <ul class="menu-head-login">
        {% if user.is_anonymous %}
            <li><a href="{{ url }}/authentication/register/"><i class="fa fa-user" aria-hidden="true"></i> Зарегистрироваться</a></li>
            <li><a href="{{ url }}/personal_room/profile/"><i class="fa fa-key" aria-hidden="true"></i> Личный кабинет</a></li>
            <li><a href="{{ url }}/authentication/login/"><i class="fa fa-sign-in" aria-hidden="true"></i> Вход</a></li>
        {% else %}
            <li><span style="font-size: 15px">Вы вошли как </span><a href="{{ url }}/personal_room/profile/">{{ user }}</a></li>
            <li><a href="{{ url }}/personal_room/"><i class="fa fa-key" aria-hidden="true"></i> Личный кабинет</a></li>
            <li><a href="{{ url }}/authentication/logout"><i class="fa fa-sign-in" aria-hidden="true"></i> Выход</a></li>
        {% endif %}
    </ul>
    <div class="basket">
        <div class="basket-text">
            ВАША КОРЗИНА</div>
        <div class="basket-icon"></div>
        <div class="basket-info">
            <span class="basket-product">Товаров: <span class="count-for-basket" id="count">{{ number_product_in_basket }}</span></span>
            <span class="basket-price">На сумму: <span class="count-for-basket" id="count-price">{{ total_amount }} р.</span></span>
        </div>
        <div class="basket-order"><button onclick="location.href='/basket/';" class="btn btn-success">Оформить заказ</button></div>
    </div>
    <div id="info">
        <i class="fa fa-info-circle" aria-hidden="true"></i>
    </div>
    <script>
        $('#info').on('click', function () {
            var block = $('#welcome-block');
            if (block.css('display') === 'none') {
                block.show(300)
            } else {
                block.hide(300)
            }
        })
    </script>
</div>

Core/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static '../static/js/product.js' %}"></script>
    <script src="{% static '../static/js/banner.js' %}"></script>
    <title>Главная - Интернет магазин здорового питания!</title>
{% endblock %}

Core/templates/leftbar.html
<ul id="menu" class="nav nav-cat" style = "background: white;">
    {% for category in category_list %}
        <li class="change-color">
            <a href="{{ category.get_absolute_url }}">
                <i class="fa fa-chevron-right" aria-hidden="true"></i> {{ category }}
            </a>
        </li>
    {% endfor %}
</ul>

Core/templates/products_list.html
<div class="col-xs-4 products" style="margin-bottom: 26px">
    <div class="product">
        <div onclick="location.href='{{ product.get_absolute_url }}'">
            <div class="tittle-product">{{ product.name }}</div>
            <div class="image-product">
                {% with product.imageproduct_set.all|first as item %}
                    <img src="{{ url }}/media/{{ item.image_resize }}" alt="">
                {% endwith %}
            </div>
            {% if product.new_price %}
                <div class="price-product">
                    <span class="no-price">{{ product.price }}</span>
                    <span>{{ product.new_price }} руб.</span>
                </div>
            {% else %}
                <div class="price-product">{{ product.price }} руб.</div>
            {% endif %}
            <div class="icon-product">
                {% if '0' in product.icon_value %}
                    <div class="icon-product-item new">
                        <div id="marker-new" style="padding-top: 4px">new</div>
                    </div>
                {% endif %}
                {% if '1' in product.icon_value %}
                    <div class="icon-product-item hit">
                        <div id="marker-hit" style="padding-top: 4px">Hit</div>
                    </div>
                {% endif %}
                {% if product.new_price %}
                    <div class="icon-product-item precent">
                        <div style="padding-top: 4px">-{{ product.sail_procent }}%</div>
                    </div>
                {% endif %}
            </div>
        </div>
        <form class="form-product" method="POST" action="/basket/add_product_in_basket">{% csrf_token %}
            <input name="id" hidden type="text" value="{{ product.id }}">
            <div class="add-product-basket">
                {% if product.availability %}
                    <div class="add-basket">
                        <button id="{{ product.id }}" class="btn btn-warning basket-button" type="submit">
                            <i class="fa fa-cart-plus" aria-hidden="true" style="color: #bdff18; font-size: 20px"></i> В корзину
                        </button>
                    </div>
                    <div class="count-product">
                        <span class="glyphicon glyphicon-minus minplus down"></span><input class="input-count" name="count" type="text" value="1"><span class="glyphicon glyphicon-plus minplus up"></span>
                        <input hidden class="max-count-product" value="{{ product.number }}">
                    </div>
                {% else %}
                    <div class="add-basket">
                        <button disabled class="btn btn-warning" style="background: gray; border: none" type="button">
                            Нет в наличии
                        </button>
                    </div>
                {% endif %}
            </div>
        </form>
    </div>
</div>

Core/templates/welcome_block.html
    <div style="
            {% if welcome %}
                display: none
            {% endif %}" id="welcome-block">
        Если во время тестирования вы заметили <u>ошибки</u> и/или <u>недоработки</u>, пожалуйста,<br> оповестите меня об этом по почте <b>den@beloglazov.me</b> <br><br>
        Используемые технологии: <br>
        - <u>Backend</u>: <b>Python</b>, <b>Django 2.0</b>. D качестве базы данных - <b>PostgreSQL</b>. Для ассинхронных задач <b>Celery</b> + <b>Redis</b>.<br>
        - <u>Frontend</u>: <b>Jquery</b>, <b>Ajax</b>, <b>Bootstrap</b>. + использование <b>встроенного Django шаблонизатора</b>. <br>
        - Магазин расположен и работает под <b>Ubuntu 16.04 + nginx + wsgi</b>. <br><br>
        Если у вас есть коммерческое предложение, пожалуйста, свяжитесь со мной по почте <b>den@beloglazov.me</b>
        <br>
    </div>